// src/views/orthographe/les-accents.vue
<!-- view-meta: created=2026-08-31; updated=2026-08-31 -->
<template>
  <AltLayout title="Les accents et la cédille">
    <main class="lesson">

      <div class="rule">
        En français, l'accent ne dit <strong class="hl-red">jamais</strong> où se trouve
        l'accent tonique. Il fait l'un de trois métiers&nbsp;: il
        <strong class="hl-blue">change le son</strong> de la lettre, il
        <strong class="hl-blue">sépare deux mots</strong> qui s'écrivent pareil, ou il ne
        change rien du tout et garde la trace d'une lettre disparue.
      </div>
      <div class="attention">
        💡 <strong>Tip para hispanohablantes&nbsp;:</strong> en español la tilde marca la
        <strong>sílaba tónica</strong> y nunca cambia el sonido de la vocal&nbsp;:
        <em>café</em> y <em>cafe</em> sonarían igual. En francés es al revés&nbsp;: el acento
        <strong class="hl-blue">cambia la vocal</strong>, y el acento tónico cae siempre en
        la última sílaba sin escribirse nunca. No busques la sílaba fuerte&nbsp;: mira el sonido.
      </div>

      <!-- ── Les cinq signes ─────────────────────── -->
      <article>
        <h2>1. Les cinq signes</h2>
        <table>
          <caption class="sr-only">Les cinq signes diacritiques du français</caption>
          <thead>
            <tr><th>Signe</th><th>Son nom</th><th>Sur quelles lettres</th><th>Exemple</th></tr>
          </thead>
          <tbody>
            <tr>
              <td><strong class="hl-blue">é</strong></td><td>l'accent aigu</td>
              <td>sur le <strong>e</strong> seulement</td><td>f<strong>é</strong>vrier</td>
            </tr>
            <tr>
              <td><strong class="hl-blue">è à ù</strong></td><td>l'accent grave</td>
              <td>e, a, u</td><td>p<strong>è</strong>re, l<strong>à</strong>, o<strong>ù</strong></td>
            </tr>
            <tr>
              <td><strong class="hl-blue">ê â î ô û</strong></td><td>l'accent circonflexe</td>
              <td>les cinq voyelles</td><td>m<strong>ê</strong>me, h<strong>ô</strong>pital</td>
            </tr>
            <tr>
              <td><strong class="hl-blue">ë ï ü</strong></td><td>le tréma</td>
              <td>e, i, u</td><td>No<strong>ë</strong>l, ma<strong>ï</strong>s</td>
            </tr>
            <tr>
              <td><strong class="hl-blue">ç</strong></td><td>la cédille</td>
              <td>sous le <strong>c</strong> seulement</td><td>fran<strong>ç</strong>ais</td>
            </tr>
          </tbody>
        </table>
        <div class="note">
          Un accent fait partie du mot, comme une lettre&nbsp;: <em>ou</em> et <em>où</em> ne
          sont pas le même mot, et <em>eleve</em> ne veut rien dire. L'oublier est une faute
          d'orthographe, pas une négligence de frappe.
        </div>
      </article>

      <!-- ── é / è : le son change ───────────────── -->
      <article>
        <h2>2. Quand l'accent change le son&nbsp;: é et è</h2>
        <p class="method">
          C'est le métier le plus important. Sur le <strong>e</strong>, l'accent décide de
          la bouche&nbsp;: fermée pour <strong class="hl-blue">é</strong>, ouverte pour
          <strong class="hl-blue">è</strong>.
        </p>

        <table>
          <caption class="sr-only">Les deux sons du e accentué</caption>
          <thead>
            <tr><th>Lettre</th><th>Son</th><th>La bouche</th><th>Exemples</th></tr>
          </thead>
          <tbody>
            <tr>
              <td><strong class="hl-blue">é</strong></td><td><em>/e/</em></td>
              <td>presque fermée&nbsp;: c'est le <em>e</em> espagnol de <em>pero</em></td>
              <td>caf<strong>é</strong>, <strong>é</strong>cole, parl<strong>é</strong></td>
            </tr>
            <tr>
              <td><strong class="hl-blue">è ê</strong></td><td><em>/ɛ/</em></td>
              <td>nettement plus ouverte&nbsp;: ce son n'existe pas en espagnol</td>
              <td>p<strong>è</strong>re, t<strong>ê</strong>te, apr<strong>è</strong>s</td>
            </tr>
          </tbody>
        </table>

        <p class="method">Trois repères suffisent pour choisir&nbsp;:</p>

        <table class="dense">
          <caption class="sr-only">Comment savoir s'il faut é, è ou rien</caption>
          <thead>
            <tr><th>Si le e est…</th><th>On écrit</th><th>Exemples</th></tr>
          </thead>
          <tbody>
            <tr>
              <td>à la fin du mot, tout seul</td>
              <td><strong class="hl-blue">é</strong></td>
              <td>l'ann<strong>ée</strong>, le march<strong>é</strong>, il a mang<strong>é</strong></td>
            </tr>
            <tr>
              <td>suivi d'une consonne + un <em>e</em> muet</td>
              <td><strong class="hl-blue">è</strong></td>
              <td>le p<strong>è</strong>re, la m<strong>è</strong>re, la r<strong>è</strong>gle</td>
            </tr>
            <tr>
              <td>suivi de deux consonnes, ou fermant le mot</td>
              <td><strong class="hl-red">rien du tout</strong></td>
              <td>elle, cette, la m<strong>e</strong>r, av<strong>e</strong>c</td>
            </tr>
          </tbody>
        </table>

        <div class="exception">
          <strong>La troisième ligne est le vrai piège.</strong> <em>Mer</em>, <em>elle</em> et
          <em>avec</em> se prononcent avec le son ouvert <em>/ɛ/</em>, exactement comme
          <em>père</em> — mais ils ne prennent <strong class="hl-red">aucun accent</strong>.
          On n'écrit jamais <em class="hl-red">mèr</em> ni <em class="hl-red">èlle</em>.
        </div>

        <div class="example">
          l'él<strong class="hl-blue">è</strong>ve
          <span class="note">(el alumno — un é fermé, puis un è ouvert, dans le même mot)</span>
        </div>
      </article>

      <!-- ── L'accent qui sépare deux mots ───────── -->
      <article>
        <h2>3. Quand l'accent sépare deux mots</h2>
        <p class="method">
          Ici l'accent ne s'entend pas du tout&nbsp;: les deux mots se prononcent de la même
          façon. Il ne sert qu'à les distinguer <strong>à l'écrit</strong>.
        </p>

        <table class="dense">
          <caption class="sr-only">Les mots que seul l'accent distingue</caption>
          <thead>
            <tr><th>Sans accent</th><th>Avec accent</th><th>En espagnol</th></tr>
          </thead>
          <tbody>
            <tr>
              <td><strong>a</strong> — il <strong>a</strong> faim</td>
              <td><strong class="hl-blue">à</strong> — <strong>à</strong> Paris</td>
              <td><em>tiene · en / a</em></td>
            </tr>
            <tr>
              <td><strong>ou</strong> — thé <strong>ou</strong> café</td>
              <td><strong class="hl-blue">où</strong> — <strong>où</strong> es-tu ?</td>
              <td><em>o · dónde</em></td>
            </tr>
            <tr>
              <td><strong>la</strong> — <strong>la</strong> maison</td>
              <td><strong class="hl-blue">là</strong> — il est <strong>là</strong></td>
              <td><em>la · allí</em></td>
            </tr>
            <tr>
              <td><strong>sur</strong> — <strong>sur</strong> la table</td>
              <td><strong class="hl-blue">sûr</strong> — je suis <strong>sûr</strong></td>
              <td><em>sobre · seguro</em></td>
            </tr>
            <tr>
              <td><strong>du</strong> — <strong>du</strong> pain</td>
              <td><strong class="hl-blue">dû</strong> — il a <strong>dû</strong> partir</td>
              <td><em>del / algo de · tenido que</em></td>
            </tr>
          </tbody>
        </table>

        <div class="note">
          Les tests pour ne plus les confondre — remplacer <em>a</em> par <em>avait</em>,
          <em>ou</em> par <em>ou bien</em> — sont sur la page qui leur est consacrée.
          <RouterLink class="lesson-link" to="/orthographe/les-homophones">
            Voir la leçon : Les homophones grammaticaux</RouterLink>
        </div>
      </article>

      <!-- ── Circonflexe et tréma ────────────────── -->
      <article>
        <h2>4. Le circonflexe et le tréma</h2>
        <p class="method">
          L'accent circonflexe est souvent le fantôme d'un <strong class="hl-red">s</strong>
          que le français a perdu il y a des siècles. L'espagnol, lui, l'a gardé&nbsp;: c'est
          un raccourci qui marche très souvent.
        </p>

        <table class="dense">
          <caption class="sr-only">Le circonflexe français face au s conservé en espagnol</caption>
          <thead>
            <tr><th>Français</th><th>L'espagnol garde le s</th><th>Français</th><th>L'espagnol garde le s</th></tr>
          </thead>
          <tbody>
            <tr>
              <td>l'h<strong class="hl-blue">ô</strong>pital</td><td><em>el ho<strong>s</strong>pital</em></td>
              <td>la p<strong class="hl-blue">â</strong>te</td><td><em>la pa<strong>s</strong>ta</em></td>
            </tr>
            <tr>
              <td>l'<strong class="hl-blue">î</strong>le</td><td><em>la i<strong>s</strong>la</em></td>
              <td>le v<strong class="hl-blue">ê</strong>tement</td><td><em>el ve<strong>s</strong>tido</em></td>
            </tr>
            <tr>
              <td>la f<strong class="hl-blue">ê</strong>te</td><td><em>la fie<strong>s</strong>ta</em></td>
              <td>le go<strong class="hl-blue">û</strong>t</td><td><em>el gu<strong>s</strong>to</em></td>
            </tr>
            <tr>
              <td>la c<strong class="hl-blue">ô</strong>te</td><td><em>la co<strong>s</strong>ta</em></td>
              <td>ao<strong class="hl-blue">û</strong>t</td><td><em>ago<strong>s</strong>to</em></td>
            </tr>
          </tbody>
        </table>

        <div class="note">
          Sur le <strong>e</strong>, le circonflexe se prononce comme un
          <strong class="hl-blue">è</strong> ouvert (<em>tête</em>, <em>fenêtre</em>). Sur les
          autres voyelles, il ne s'entend presque pas&nbsp;: <em>pâte</em>, <em>île</em>,
          <em>août</em>.
        </div>

        <p class="method">
          Le <strong class="hl-blue">tréma</strong> dit une seule chose&nbsp;: «&nbsp;ces deux
          voyelles se prononcent <strong>séparément</strong>&nbsp;».
        </p>

        <div class="example">
          No<strong class="hl-blue">ë</strong>l se dit <em>no-el</em>, pas «&nbsp;neul&nbsp;»
          <span class="sep">·</span>
          le ma<strong class="hl-blue">ï</strong>s se dit <em>ma-is</em>, pas «&nbsp;mè&nbsp;»
          <span class="sep">·</span>
          na<strong class="hl-blue">ï</strong>f se dit <em>na-if</em>
          <span class="note">(Navidad · el maíz · ingenuo)</span>
        </div>
        <div class="attention">
          C'est exactement le rôle du <strong>ü</strong> espagnol dans
          <em>pingüino</em> ou <em>vergüenza</em>&nbsp;: sans le tréma, la voyelle serait
          avalée par sa voisine. Le français applique la même idée, sur d'autres lettres.
        </div>
      </article>

      <!-- ── La cédille ──────────────────────────── -->
      <article>
        <h2>5. La cédille</h2>
        <div class="rule">
          Le <strong>c</strong> se prononce <em>/s/</em> devant <strong>e</strong> et
          <strong>i</strong>, mais <em>/k/</em> devant <strong>a</strong>, <strong>o</strong>
          et <strong>u</strong>. La cédille sert à garder le son <em>/s/</em> devant ces
          trois voyelles-là.
        </div>

        <table class="dense">
          <caption class="sr-only">Quand écrire c et quand écrire ç</caption>
          <thead>
            <tr><th>Devant</th><th>On écrit</th><th>Son</th><th>Exemples</th></tr>
          </thead>
          <tbody>
            <tr>
              <td>e, i</td><td><strong class="hl-blue">c</strong></td><td><em>/s/</em></td>
              <td>le <strong>ci</strong>néma, dou<strong>ce</strong></td>
            </tr>
            <tr>
              <td>a, o, u</td><td><strong class="hl-blue">ç</strong></td><td><em>/s/</em></td>
              <td>fran<strong>ç</strong>ais, gar<strong>ç</strong>on, il a re<strong>ç</strong>u</td>
            </tr>
            <tr>
              <td>a, o, u</td><td><strong class="hl-blue">c</strong></td><td><em>/k/</em></td>
              <td>le <strong>ca</strong>fé, l'é<strong>co</strong>le, é<strong>cou</strong>ter</td>
            </tr>
          </tbody>
        </table>

        <div class="exception">
          <strong>Jamais de cédille devant e ni i.</strong> Le <em>c</em> y est déjà doux, la
          cédille n'aurait rien à faire&nbsp;: on écrit <em>ce</em>, <em>ci</em>,
          <em>cinéma</em> — et jamais <em class="hl-red">çe</em> ni <em class="hl-red">çi</em>.
        </div>

        <div class="example">
          nous commen<strong class="hl-blue">ç</strong>ons
          <span class="sep">·</span>
          mais nous commen<strong>c</strong>ions
          <span class="note">(empezamos · empezábamos — devant le i, la cédille tombe)</span>
        </div>
        <div class="note">
          C'est la règle qui fait bouger tous les verbes en <strong>-cer</strong>.
          <RouterLink class="lesson-link" to="/conjugaison/commencer">
            Voir le tableau : commencer</RouterLink>
        </div>
      </article>

      <RelatedLinks />
    </main>
  </AltLayout>
</template>

<script setup>
import { RouterLink } from 'vue-router'
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'
</script>

// src/app/orthographe/les-accents/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/orthographe/les-accents";

export const metadata = lessonMetadata(PATH);

export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>Ce qu’un accent français fait, et ne fait pas</h2>

        <div className="rule">
          L’accent français ne dit <strong>jamais</strong> où tombe la syllabe
          forte. Il fait l’un de trois métiers : il{" "}
          <strong>change le son</strong> de la voyelle, il{" "}
          <strong>sépare deux mots</strong> qui s’écriraient pareil, ou il ne
          s’entend pas du tout.
        </div>

        <p>
          C’est pour cela qu’on ne peut pas placer un accent à l’oreille, en
          cherchant l’endroit où l’on appuie. En français, on appuie toujours
          sur la fin du mot, et cela ne s’écrit nulle part.
        </p>

        <div className="table-wrap">
          <table>
            <caption>
              Les cinq signes, et les lettres sur lesquelles chacun peut se
              poser
            </caption>
            <thead>
              <tr>
                <th scope="col">Signe</th>
                <th scope="col">Son nom</th>
                <th scope="col">Sur quelles lettres</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  é
                </th>
                <td>l’accent aigu</td>
                <td>
                  sur le <span className="fr">e</span> seulement
                </td>
                <td className="fr">février</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  è à ù
                </th>
                <td>l’accent grave</td>
                <td>
                  sur <span className="fr">e</span>,{" "}
                  <span className="fr">a</span>, <span className="fr">u</span>
                </td>
                <td className="fr">père · là · où</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ê â î ô û
                </th>
                <td>l’accent circonflexe</td>
                <td>sur les cinq voyelles</td>
                <td className="fr">même · hôpital · août</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ë ï ü
                </th>
                <td>le tréma</td>
                <td>
                  sur <span className="fr">e</span>,{" "}
                  <span className="fr">i</span>, <span className="fr">u</span>
                </td>
                <td className="fr">Noël · maïs</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ç
                </th>
                <td>la cédille</td>
                <td>
                  sous le <span className="fr">c</span> seulement
                </td>
                <td className="fr">français</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p>
          Le tréma dit une seule chose : les deux voyelles se prononcent{" "}
          <strong>séparément</strong>. <span className="fr">Noël</span> se dit
          en deux temps, <span className="fr">maïs</span> aussi. Sans le tréma,
          la première voyelle serait avalée par la seconde.
        </p>

        <div className="attention">
          un accent fait partie du mot, au même titre qu’une lettre. Écrire{" "}
          <span className="fr">eleve</span> pour{" "}
          <span className="fr">élève</span> n’est pas une frappe manquée, c’est
          une faute d’orthographe. Et{" "}
          <span className="fr">ou</span> et <span className="fr">où</span> ne
          sont pas le même mot : les tests qui les séparent sont sur{" "}
          <span className="fr">Les homophones</span>.
        </div>
      </section>

      <section>
        <h2>Sur le e : é, è, ou rien du tout</h2>

        <div className="rule">
          C’est le métier le plus important, et le seul qui s’entende. Sur le{" "}
          <span className="fr">e</span>, l’accent décide de la bouche : presque
          fermée pour <span className="fr">é</span>, nettement ouverte pour{" "}
          <span className="fr">è</span> et <span className="fr">ê</span>.
        </div>

        <div className="example">
          <span className="fr">é</span> : café · école · vous avez parlé
          <br />
          <span className="fr">è ê</span> : père · après · tête · fenêtre
        </div>

        <p>
          Le son ne suffit pourtant pas à choisir, parce que le même son ouvert
          s’écrit tantôt avec un accent, tantôt sans. Trois repères suffisent, et
          ils regardent ce qui suit le <span className="fr">e</span>.
        </p>

        <div className="table-wrap">
          <table>
            <caption>Ce qui suit le e décide de l’accent qu’il porte</caption>
            <thead>
              <tr>
                <th scope="col">Si le e est…</th>
                <th scope="col">On écrit</th>
                <th scope="col">Exemples</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">
                  en fin de mot, suivi au plus d’un e ou d’un s muet
                </th>
                <td className="fr">é</td>
                <td className="fr">le marché · l’année · il a mangé</td>
              </tr>
              <tr>
                <th scope="row">suivi d’une consonne, puis d’un e muet</th>
                <td className="fr">è</td>
                <td className="fr">le père · la mère · la règle</td>
              </tr>
              <tr>
                <th scope="row">suivi de deux consonnes, ou fermant le mot</th>
                <td>rien</td>
                <td className="fr">elle · cette · la mer · avec</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="exception">
          la troisième ligne est le vrai piège.{" "}
          <span className="fr">mer</span>, <span className="fr">elle</span> et{" "}
          <span className="fr">avec</span> se prononcent avec le son ouvert,
          exactement comme <span className="fr">père</span>, et pourtant ils ne
          portent aucun accent. On n’écrit jamais{" "}
          <span className="fr">mèr</span> ni <span className="fr">èlle</span>.
        </div>

        <div className="astuce">
          <p className="astuce-hook">
            Un mot peut porter les deux, dans cet ordre.
          </p>
          <p>
            <span className="fr">l’élève</span> commence par un{" "}
            <span className="fr">é</span> fermé et finit par un{" "}
            <span className="fr">è</span> ouvert. Lisez le mot lentement et vous
            entendrez les deux bouches. C’est le meilleur mot à garder en tête
            pour vérifier que vous entendez la différence.
          </p>
        </div>
      </section>

      <section>
        <h2>La cédille</h2>

        <div className="rule">
          Le <span className="fr">c</span> se prononce comme un{" "}
          <span className="fr">s</span> devant{" "}
          <span className="fr">e</span> et <span className="fr">i</span>, et
          comme un <span className="fr">k</span> devant{" "}
          <span className="fr">a</span>, <span className="fr">o</span> et{" "}
          <span className="fr">u</span>. La cédille sert à garder le son{" "}
          <span className="fr">s</span> devant ces trois voyelles-là.
        </div>

        <div className="table-wrap">
          <table>
            <caption>
              Quand le c suffit et quand il faut lui mettre une cédille
            </caption>
            <thead>
              <tr>
                <th scope="col">Devant</th>
                <th scope="col">On écrit</th>
                <th scope="col">Se prononce</th>
                <th scope="col">Exemples</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  e, i
                </th>
                <td className="fr">c</td>
                <td className="fr">s</td>
                <td className="fr">le cinéma · douce</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  a, o, u
                </th>
                <td className="fr">ç</td>
                <td className="fr">s</td>
                <td className="fr">français · un garçon · il a reçu</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  a, o, u
                </th>
                <td className="fr">c</td>
                <td className="fr">k</td>
                <td className="fr">le café · l’école · écouter</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="exception">
          jamais de cédille devant <span className="fr">e</span> ni{" "}
          <span className="fr">i</span>. Le <span className="fr">c</span> y est
          déjà doux, la cédille n’aurait rien à y faire : on écrit{" "}
          <span className="fr">ce</span>, <span className="fr">ci</span>,{" "}
          <span className="fr">cinéma</span>, et jamais{" "}
          <span className="fr">çe</span> ni <span className="fr">çi</span>.
        </div>

        <div className="example">
          nous commen<strong>ç</strong>ons · mais nous commen<strong>c</strong>
          ions
        </div>

        <div className="attention">
          la cédille ne se tape pas sur un clavier espagnol, et{" "}
          <span className="fr">œ</span> non plus. Ce n’est pas une raison pour
          les laisser tomber : <span className="fr">francais</span> et{" "}
          <span className="fr">soeur</span> sont des fautes. Copiez le
          caractère, ou passez le clavier en français le temps d’écrire.
        </div>
      </section>

      <div className="resume">
        <h2>En résumé</h2>
        <ul>
          <li>
            L’accent français ne marque pas la syllabe forte : il change le son,
            il sépare deux mots, ou il ne s’entend pas.
          </li>
          <li>
            Cinq signes : <span className="fr">é</span> aigu,{" "}
            <span className="fr">è à ù</span> grave,{" "}
            <span className="fr">ê â î ô û</span> circonflexe,{" "}
            <span className="fr">ë ï ü</span> tréma,{" "}
            <span className="fr">ç</span> cédille.
          </li>
          <li>
            Sur le <span className="fr">e</span>, c’est ce qui suit qui décide :{" "}
            <span className="fr">é</span> en fin de mot,{" "}
            <span className="fr">è</span> devant consonne plus{" "}
            <span className="fr">e</span> muet, rien devant deux consonnes.
          </li>
          <li>
            <span className="fr">mer</span>, <span className="fr">elle</span>,{" "}
            <span className="fr">avec</span> sonnent ouvert et ne prennent
            pourtant aucun accent.
          </li>
          <li>
            La cédille garde le son <span className="fr">s</span> devant{" "}
            <span className="fr">a</span>, <span className="fr">o</span>,{" "}
            <span className="fr">u</span>, et ne s’écrit jamais devant{" "}
            <span className="fr">e</span> ni <span className="fr">i</span>.
          </li>
        </ul>
      </div>
    </article>
  );
}
