// src/views/grammaire/passe-compose-ou-imparfait.vue
<!-- view-meta: created=2026-08-10; updated=2026-08-10 -->
<template>
  <AltLayout title="Passé composé ou imparfait ?">
    <main class="lesson">

      <!-- ── Règle ─────────────────────────────────── -->
      <article>
        <div class="rule">
          Les deux temps parlent du passé, mais ils ne racontent pas la même chose.
          Le <strong class="hl-blue">passé composé</strong> raconte <strong>ce qui est arrivé</strong>&nbsp;;
          l'<strong class="hl-blue">imparfait</strong> décrit <strong>le décor</strong> autour.
        </div>
        <div class="attention">
          💡 <strong>Tip para hispanohablantes&nbsp;:</strong> ya conoces esta diferencia&nbsp;—
          es la misma que entre <strong>comí</strong> (indefinido) y <strong>comía</strong> (imperfecto).
          El <em>passé composé</em> corresponde a tu indefinido, el <em>imparfait</em> a tu imperfecto.
          <strong>Fíate de tu intuición de español</strong>&nbsp;: acierta casi siempre.
        </div>
      </article>

      <!-- ── Le contraste ───────────────────────────── -->
      <article>
        <h2>1. Action ou décor&nbsp;?</h2>

        <table>
          <caption class="sr-only">Comparaison des emplois du passé composé et de l'imparfait</caption>
          <thead>
            <tr>
              <th></th>
              <th>Passé composé</th>
              <th>Imparfait</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="person">Rôle</td>
              <td class="aux">l'action</td>
              <td class="aux">le décor</td>
            </tr>
            <tr>
              <td class="person">Question</td>
              <td>Qu'est-ce qui s'est passé&nbsp;?</td>
              <td>Comment c'était&nbsp;?</td>
            </tr>
            <tr>
              <td class="person">Durée</td>
              <td>terminée, limitée</td>
              <td>non limitée</td>
            </tr>
            <tr>
              <td class="person">Combien de fois</td>
              <td>une fois, un nombre précis</td>
              <td>souvent, tous les jours</td>
            </tr>
            <tr>
              <td class="person">Espagnol</td>
              <td class="translation">comí, hablé, fui</td>
              <td class="translation">comía, hablaba, iba</td>
            </tr>
          </tbody>
        </table>

        <div class="example">
          Il <strong class="hl-blue">faisait</strong> nuit et je <strong class="hl-blue">dormais</strong>
          quand le téléphone <strong class="hl-red">a sonné</strong>.
          <span class="note">(Era de noche y dormía cuando sonó el teléfono)</span>
        </div>
        <p class="method">
          Le décor est à l'imparfait (<em>faisait, dormais</em>), l'événement qui arrive et
          coupe le décor est au passé composé (<em>a sonné</em>).
        </p>
      </article>

      <!-- ── Les mots qui aident ────────────────────── -->
      <article>
        <h2>2. Les mots qui vous mettent sur la piste</h2>

        <table>
          <caption class="sr-only">Expressions de temps associées à chaque temps du passé</caption>
          <thead>
            <tr>
              <th>Plutôt passé composé</th>
              <th>Plutôt imparfait</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>soudain, tout à coup</td>
              <td>souvent, d'habitude</td>
            </tr>
            <tr>
              <td>hier, ce matin</td>
              <td>tous les jours, chaque été</td>
            </tr>
            <tr>
              <td>une fois, deux fois</td>
              <td>quand j'étais petit</td>
            </tr>
            <tr>
              <td>puis, ensuite, enfin</td>
              <td>pendant que, à cette époque</td>
            </tr>
          </tbody>
        </table>

        <div class="example">
          <strong class="hl-blue">Tous les dimanches</strong>, nous <strong>allions</strong> chez ma grand-mère.
          <span class="sep">·</span>
          <strong class="hl-red">Dimanche dernier</strong>, nous <strong>sommes allés</strong> au cinéma.
        </div>
      </article>

      <!-- ── À retenir ──────────────────────────────── -->
      <article>
        <div class="attention">
          Dans une histoire, les deux temps travaillent ensemble&nbsp;: l'imparfait <strong>plante
          le décor</strong>, le passé composé <strong>fait avancer l'histoire</strong>.
          Si vous pouvez remplacer par «&nbsp;était en train de&nbsp;», c'est l'imparfait.
        </div>
      </article>

      <!-- ── Exception ──────────────────────────────── -->
      <article>
        <div class="exception">
          <strong>Attention au changement de sens.</strong> Certains verbes changent de signification
          selon le temps choisi. Ce n'est pas une faute de grammaire&nbsp;: c'est une autre phrase.
        </div>
        <div class="example exception-ex">
          Je <strong class="hl-red">savais</strong> la réponse.
          <span class="note">(yo sabía la respuesta — état)</span>
          <br />
          J'<strong class="hl-red">ai su</strong> la réponse.
          <span class="note">(supe la respuesta — je l'ai apprise à ce moment-là)</span>
        </div>
      </article>

      <RelatedLinks />
    </main>
  </AltLayout>
</template>

<script setup>
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'
</script>

// src/app/grammaire/passe-compose-ou-imparfait/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/grammaire/passe-compose-ou-imparfait";

export const metadata = lessonMetadata(PATH);

export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>L’action ou le décor</h2>

        <div className="rule">
          Les deux temps parlent du passé, mais ils ne racontent pas la même
          chose. Le <strong>passé composé</strong> dit ce qui est{" "}
          <strong>arrivé</strong> ; l’<strong>imparfait</strong> décrit le{" "}
          <strong>décor</strong> autour.
        </div>

        <div className="table-wrap">
          <table>
            <caption>Ce que chaque temps apporte à un récit</caption>
            <thead>
              <tr>
                <th scope="col">Question</th>
                <th scope="col">Passé composé</th>
                <th scope="col">Imparfait</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">Il répond à</th>
                <td>Qu’est-ce qui s’est passé ?</td>
                <td>Comment c’était ?</td>
              </tr>
              <tr>
                <th scope="row">L’action est</th>
                <td>terminée, limitée</td>
                <td>en cours, sans limite</td>
              </tr>
              <tr>
                <th scope="row">Combien de fois</th>
                <td>une fois, un nombre précis</td>
                <td>souvent, chaque jour</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="example">
          Il <strong>faisait</strong> nuit et je <strong>dormais</strong> quand
          le téléphone <strong>a sonné</strong>.
        </div>

        <p>
          Le décor est à l’imparfait — <span className="fr">il faisait</span>,{" "}
          <span className="fr">je dormais</span>. L’événement qui arrive et qui
          coupe ce décor est au passé composé —{" "}
          <span className="fr">a sonné</span>. Changez les temps de place et
          l’histoire change : <span className="fr">Il a fait nuit</span>{" "}
          raconterait la tombée de la nuit comme un événement.
        </p>
      </section>

      <section>
        <h2>Les mots qui vous mettent sur la piste</h2>

        <p>
          Certaines expressions de temps annoncent presque toujours le même
          temps. Elles ne décident pas à votre place, mais elles indiquent la
          direction.
        </p>

        <div className="table-wrap">
          <table>
            <caption>
              Expressions de temps et temps du passé qu’elles appellent
            </caption>
            <thead>
              <tr>
                <th scope="col">Plutôt passé composé</th>
                <th scope="col">Plutôt imparfait</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="fr">soudain, tout à coup</td>
                <td className="fr">souvent, d’habitude</td>
              </tr>
              <tr>
                <td className="fr">un jour, ce matin-là</td>
                <td className="fr">tous les jours, le lundi</td>
              </tr>
              <tr>
                <td className="fr">hier, la semaine dernière</td>
                <td className="fr">à cette époque, quand j’étais petit</td>
              </tr>
              <tr>
                <td className="fr">deux fois, trois heures</td>
                <td className="fr">pendant que, toujours</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="attention">
          une durée précise ferme l’action, donc elle appelle le passé composé :{" "}
          <span className="fr">J’ai vécu dix ans à Lyon</span> — dix ans, c’est
          fini. Avec <span className="fr">Je vivais à Lyon</span>, on ne dit pas
          combien de temps, on plante le décor.
        </div>
      </section>

      <section>
        <h2>Les deux ensemble</h2>

        <p>
          Dans un vrai récit, les deux temps travaillent côte à côte. L’imparfait
          tient la scène, le passé composé fait avancer l’histoire.
        </p>

        <div className="example">
          Samedi, il <strong>pleuvait</strong> et il n’y{" "}
          <strong>avait</strong> personne dans la rue. Je{" "}
          <strong>suis sortie</strong> quand même. J’<strong>ai marché</strong>{" "}
          jusqu’à la gare, puis j’<strong>ai pris</strong> un café dans un bar
          qui <strong>venait</strong> d’ouvrir.
        </div>

        <div className="astuce">
          <p className="astuce-hook">Le test du film</p>
          <p>
            Demandez-vous si la phrase serait une <strong>photo</strong> ou une{" "}
            <strong>scène qui bouge</strong>. Une photo — le temps qu’il fait,
            l’âge de quelqu’un, ce qu’il y avait autour — c’est l’imparfait. Une
            scène où quelque chose se produit et se termine, c’est le passé
            composé. Le test se trompe surtout sur les verbes d’état comme{" "}
            <span className="fr">savoir</span> ou{" "}
            <span className="fr">vouloir</span> : au passé composé, ils
            signalent le moment précis où l’état a changé —{" "}
            <span className="fr">j’ai su</span>, c’est « à cet instant, j’ai
            appris ».
          </p>
        </div>
      </section>

      <div className="resume">
        <ul>
          <li>
            Le passé composé dit ce qui est arrivé ; l’imparfait décrit le décor
            autour.
          </li>
          <li>
            Une action terminée et limitée va au passé composé. Une situation
            sans limite, ou répétée, va à l’imparfait.
          </li>
          <li>
            Certaines expressions indiquent la direction :{" "}
            <span className="fr">soudain</span>,{" "}
            <span className="fr">un jour</span> d’un côté ;{" "}
            <span className="fr">souvent</span>,{" "}
            <span className="fr">tous les jours</span> de l’autre. Elles
            indiquent, elles ne décident pas.
          </li>
          <li>
            Une durée précise ferme l’action, donc elle appelle le passé
            composé : <span className="fr">J’ai vécu dix ans à Lyon</span>.
          </li>
          <li>
            Dans un récit, les deux se relaient : l’imparfait tient la scène, le
            passé composé la fait avancer.
          </li>
        </ul>
      </div>
    </article>
  );
}
