// src/app/grammaire/l-imparfait/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/grammaire/l-imparfait";

export const metadata = lessonMetadata(PATH);

export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>Former l’imparfait</h2>

        <div className="rule">
          On part du verbe conjugué avec <span className="fr">nous</span> au
          présent, on enlève <span className="fr">-ons</span>, et on ajoute les
          terminaisons de l’imparfait.
        </div>

        <div className="example">
          nous parl<strong>ons</strong> → parl- → je parl<strong>ais</strong>
          <br />
          nous finiss<strong>ons</strong> → finiss- → je finiss
          <strong>ais</strong>
          <br />
          nous pren<strong>ons</strong> → pren- → je pren<strong>ais</strong>
        </div>

        <div className="table-wrap">
          <table>
            <caption>Les terminaisons de l’imparfait, sur trois verbes</caption>
            <thead>
              <tr>
                <th scope="col">Sujet</th>
                <th scope="col" className="fr">
                  parler
                </th>
                <th scope="col" className="fr">
                  finir
                </th>
                <th scope="col" className="fr">
                  prendre
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">je</th>
                <td className="fr">parlais</td>
                <td className="fr">finissais</td>
                <td className="fr">prenais</td>
              </tr>
              <tr>
                <th scope="row">tu</th>
                <td className="fr">parlais</td>
                <td className="fr">finissais</td>
                <td className="fr">prenais</td>
              </tr>
              <tr>
                <th scope="row">il / elle / on</th>
                <td className="fr">parlait</td>
                <td className="fr">finissait</td>
                <td className="fr">prenait</td>
              </tr>
              <tr>
                <th scope="row">nous</th>
                <td className="fr">parlions</td>
                <td className="fr">finissions</td>
                <td className="fr">prenions</td>
              </tr>
              <tr>
                <th scope="row">vous</th>
                <td className="fr">parliez</td>
                <td className="fr">finissiez</td>
                <td className="fr">preniez</td>
              </tr>
              <tr>
                <th scope="row">ils / elles</th>
                <td className="fr">parlaient</td>
                <td className="fr">finissaient</td>
                <td className="fr">prenaient</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="attention">
          les terminaisons sont les mêmes pour <strong>tous</strong> les verbes
          du français. Quatre d’entre elles se prononcent de façon identique :{" "}
          <span className="fr">
            je parlais, tu parlais, il parlait, ils parlaient
          </span>
          . Seule l’orthographe les sépare, et elle dépend du sujet.
        </div>

        <div className="exception">
          <span className="fr">être</span>. Son radical ne vient pas du{" "}
          <span className="fr">nous</span> du présent :{" "}
          <span className="fr">
            j’étais, tu étais, il était, nous étions, vous étiez, ils étaient
          </span>
          . C’est le seul verbe irrégulier à ce temps.
        </div>
      </section>

      <section>
        <h2>Quand l’employer</h2>

        <p>
          L’imparfait ne dit pas <em>quand</em> une action a commencé ni{" "}
          <em>quand</em> elle a fini. Il installe une situation, une habitude,
          une description. Trois emplois couvrent presque tout.
        </p>

        <div className="table-wrap">
          <table>
            <caption>Les trois emplois courants de l’imparfait</caption>
            <thead>
              <tr>
                <th scope="col">Emploi</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">une description</th>
                <td className="fr">
                  Il faisait froid et la maison était vide.
                </td>
              </tr>
              <tr>
                <th scope="row">une habitude</th>
                <td className="fr">
                  Tous les étés, nous allions chez ma grand-mère.
                </td>
              </tr>
              <tr>
                <th scope="row">une action qui durait</th>
                <td className="fr">Je dormais quand tu as appelé.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="astuce">
          <p className="astuce-hook">Trois phrases à garder toutes faites</p>
          <p>
            <span className="fr">c’était</span>,{" "}
            <span className="fr">il y avait</span>,{" "}
            <span className="fr">il faisait</span> ouvrent la plupart des
            descriptions au passé : <span className="fr">C’était en 2019</span>{" "}
            · <span className="fr">Il y avait beaucoup de monde</span> ·{" "}
            <span className="fr">Il faisait très chaud</span>. Trois formes
            apprises, et le décor est planté.
          </p>
        </div>
      </section>

      <div className="resume">
        <ul>
          <li>
            Le radical vient du <span className="fr">nous</span> du présent, sans{" "}
            <span className="fr">-ons</span>.
          </li>
          <li>
            Les terminaisons sont les mêmes pour tous les verbes :{" "}
            <span className="fr">-ais, -ais, -ait, -ions, -iez, -aient</span>.
          </li>
          <li>
            Quatre d’entre elles se prononcent de la même façon. Seule
            l’orthographe les sépare, et elle dépend du sujet.
          </li>
          <li>
            <span className="fr">être</span> est le seul verbe irrégulier :{" "}
            <span className="fr">j’étais</span>.
          </li>
          <li>
            Trois emplois : la description, l’habitude, l’action qui durait.
          </li>
        </ul>
      </div>
    </article>
  );
}

// src/views/grammaire/l-imparfait.vue
<!-- view-meta: created=2026-08-10; updated=2026-08-10 -->
<template>
  <AltLayout title="L'imparfait">
    <main class="lesson">

      <!-- ── Règle ─────────────────────────────────── -->
      <article>
        <div class="rule">
          L'<strong class="hl-blue">imparfait</strong> est un temps du passé. Il décrit une situation,
          une habitude ou une action qui <strong>durait</strong>, sans dire quand elle a commencé
          ni quand elle a fini.
        </div>
        <div class="attention">
          💡 <strong>Tip para hispanohablantes&nbsp;:</strong> el <em>imparfait</em> es exactamente
          tu <strong class="hl-blue">pretérito imperfecto</strong> (<em>hablaba, comía, vivía</em>).
          Se usa igual y casi siempre se traduce igual. Es de los temas más fáciles del francés
          para ti&nbsp;: lo que tienes que aprender son las <strong>terminaciones</strong>.
        </div>
      </article>

      <!-- ── Formation ──────────────────────────────── -->
      <article>
        <h2>1. La formation</h2>
        <p class="method">
          On prend le verbe conjugué à la 1<sup>re</sup> personne du pluriel du présent
          (<strong>nous</strong>), on enlève <strong>-ons</strong>, et on ajoute les terminaisons.
        </p>
        <p class="method-example">
          <strong>nous parl<span class="hl-red">ons</span></strong>
          <span class="arrow-inline" aria-hidden="true">→</span>
          <strong>parl-</strong>
          <span class="arrow-inline" aria-hidden="true">+</span>
          <strong class="hl-blue">-ais, -ais, -ait, -ions, -iez, -aient</strong>
        </p>

        <table>
          <caption class="sr-only">Conjugaison de trois verbes à l'imparfait</caption>
          <thead>
            <tr>
              <th>Pronom</th>
              <th>parler</th>
              <th>finir</th>
              <th>Traducción (ES)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="person">je</td>
              <td class="aux">parlais</td>
              <td>finissais</td>
              <td class="translation">hablaba / terminaba</td>
            </tr>
            <tr>
              <td class="person">tu</td>
              <td class="aux">parlais</td>
              <td>finissais</td>
              <td class="translation">hablabas / terminabas</td>
            </tr>
            <tr>
              <td class="person">il / elle / on</td>
              <td class="aux">parlait</td>
              <td>finissait</td>
              <td class="translation">hablaba / terminaba</td>
            </tr>
            <tr>
              <td class="person">nous</td>
              <td class="aux">parlions</td>
              <td>finissions</td>
              <td class="translation">hablábamos / terminábamos</td>
            </tr>
            <tr>
              <td class="person">vous</td>
              <td class="aux">parliez</td>
              <td>finissiez</td>
              <td class="translation">hablabais / terminabais</td>
            </tr>
            <tr>
              <td class="person">ils / elles</td>
              <td class="aux">parlaient</td>
              <td>finissaient</td>
              <td class="translation">hablaban / terminaban</td>
            </tr>
          </tbody>
        </table>

        <div class="attention">
          Les terminaisons sont <strong>les mêmes pour tous les verbes</strong>, sans aucune exception.
          Quatre d'entre elles se prononcent de façon identique&nbsp;:
          <em>parlais, parlais, parlait, parlaient</em>.
        </div>
      </article>

      <!-- ── Emplois ────────────────────────────────── -->
      <article>
        <h2>2. Quand l'utiliser</h2>

        <table>
          <caption class="sr-only">Les trois emplois de l'imparfait</caption>
          <thead>
            <tr>
              <th>Emploi</th>
              <th>Exemple</th>
              <th>Traducción (ES)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="aux">Une habitude</td>
              <td>Tous les étés, nous <strong>allions</strong> à la mer.</td>
              <td class="translation">Todos los veranos íbamos al mar.</td>
            </tr>
            <tr>
              <td class="aux">Une description</td>
              <td>Il <strong>faisait</strong> beau et les oiseaux <strong>chantaient</strong>.</td>
              <td class="translation">Hacía bueno y los pájaros cantaban.</td>
            </tr>
            <tr>
              <td class="aux">Une action en cours</td>
              <td>Je <strong>dormais</strong> quand tu as téléphoné.</td>
              <td class="translation">Dormía cuando llamaste.</td>
            </tr>
          </tbody>
        </table>

        <div class="example">
          Quand j'<strong class="hl-blue">étais</strong> petit, j'<strong class="hl-blue">avais</strong> un chien.
          <span class="note">(Cuando era pequeño, tenía un perro)</span>
        </div>
      </article>

      <!-- ── Exceptions ─────────────────────────────── -->
      <article>
        <div class="exception">
          <strong>Un seul verbe irrégulier&nbsp;: être.</strong> Son radical est
          <strong class="hl-red">ét-</strong> (j'étais, tu étais, il était, nous étions, vous étiez,
          ils étaient). Tous les autres verbes, même les plus irréguliers, suivent la règle du
          «&nbsp;nous&nbsp;»&nbsp;: <em>nous faisons</em> → je <strong>faisais</strong>,
          <em>nous buvons</em> → je <strong>buvais</strong>.
        </div>
        <div class="example exception-ex">
          Les verbes en <strong class="hl-red">-ger</strong> et <strong class="hl-red">-cer</strong>
          gardent le son doux&nbsp;: je man<strong class="hl-red">ge</strong>ais,
          nous commen<strong class="hl-red">ç</strong>ions.
        </div>
      </article>

      <RelatedLinks />
    </main>
  </AltLayout>
</template>

<script setup>
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'
</script>
