// src/app/grammaire/le-passe-compose/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/grammaire/le-passe-compose";

export const metadata = lessonMetadata(PATH);

/* Tout est en français (docs/decisions.md #53) : la phrase qui explique est en
   sans, l'exemple français est en serif — c'est le rôle qui décide, pas la
   langue. Server Component : pas de 'use client', pas de hook, pas d'état. */
export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>Le passé composé avec « avoir »</h2>

        <div className="rule">
          Le passé composé raconte une action <strong>terminée</strong>. On le
          forme avec un auxiliaire au présent, <span className="fr">avoir</span>{" "}
          ou <span className="fr">être</span>, suivi du{" "}
          <strong>participe passé</strong> du verbe. La grande majorité des
          verbes prennent <span className="fr">avoir</span>.
        </div>

        <div className="example">
          Hier, j’<strong>ai mangé</strong> au restaurant. · Nous{" "}
          <strong>avons fini</strong> à six heures. · Ils{" "}
          <strong>ont pris</strong> le train.
        </div>

        <div className="table-wrap">
          <table>
            <caption>Le verbe « manger » au passé composé</caption>
            <thead>
              <tr>
                <th scope="col">Sujet</th>
                <th scope="col">Auxiliaire</th>
                <th scope="col">Participe passé</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">j’</th>
                <td className="fr">ai</td>
                <td className="fr">mangé</td>
              </tr>
              <tr>
                <th scope="row">tu</th>
                <td className="fr">as</td>
                <td className="fr">mangé</td>
              </tr>
              <tr>
                <th scope="row">il / elle / on</th>
                <td className="fr">a</td>
                <td className="fr">mangé</td>
              </tr>
              <tr>
                <th scope="row">nous</th>
                <td className="fr">avons</td>
                <td className="fr">mangé</td>
              </tr>
              <tr>
                <th scope="row">vous</th>
                <td className="fr">avez</td>
                <td className="fr">mangé</td>
              </tr>
              <tr>
                <th scope="row">ils / elles</th>
                <td className="fr">ont</td>
                <td className="fr">mangé</td>
              </tr>
            </tbody>
          </table>
        </div>

        <h3>Former le participe passé</h3>

        <div className="table-wrap">
          <table>
            <caption>La terminaison du participe passé, groupe par groupe</caption>
            <thead>
              <tr>
                <th scope="col">Verbes en</th>
                <th scope="col">Participe en</th>
                <th scope="col">Exemples</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  -er
                </th>
                <td className="fr">-é</td>
                <td className="fr">parler → parlé · aimer → aimé</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  -ir
                </th>
                <td className="fr">-i</td>
                <td className="fr">finir → fini · choisir → choisi</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  -dre
                </th>
                <td className="fr">-u</td>
                <td className="fr">vendre → vendu · attendre → attendu</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="exception">
          les verbes très fréquents ont un participe à part. Il faut les
          apprendre un par un : <span className="fr">avoir → eu</span>,{" "}
          <span className="fr">être → été</span>,{" "}
          <span className="fr">faire → fait</span>,{" "}
          <span className="fr">voir → vu</span>,{" "}
          <span className="fr">prendre → pris</span>,{" "}
          <span className="fr">mettre → mis</span>,{" "}
          <span className="fr">écrire → écrit</span>,{" "}
          <span className="fr">pouvoir → pu</span>,{" "}
          <span className="fr">vouloir → voulu</span>.
        </div>
      </section>

      <section>
        <h2>Le passé composé avec « être »</h2>

        <p>
          Une petite famille de verbes n’utilise pas{" "}
          <span className="fr">avoir</span> : les verbes qui disent un{" "}
          <strong>déplacement</strong> ou un <strong>changement d’état</strong>,
          et tous les verbes pronominaux.
        </p>

        <div className="example">
          aller · venir · arriver · partir · entrer · sortir · monter ·
          descendre · naître · mourir · rester · tomber · retourner · passer
          <br />
          se lever · se coucher · se promener · s’habiller
        </div>

        <div className="rule">
          Avec <span className="fr">être</span>, le participe passé{" "}
          <strong>s’accorde avec le sujet</strong>, comme un adjectif : on
          ajoute <span className="fr">-e</span> au féminin,{" "}
          <span className="fr">-s</span> au pluriel.
        </div>

        <div className="table-wrap">
          <table>
            <caption>L’accord du participe passé avec « être »</caption>
            <thead>
              <tr>
                <th scope="col">Sujet</th>
                <th scope="col">Phrase</th>
                <th scope="col">Terminaison</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">masculin singulier</th>
                <td className="fr">Il est parti.</td>
                <td className="fr">—</td>
              </tr>
              <tr>
                <th scope="row">féminin singulier</th>
                <td className="fr">Elle est partie.</td>
                <td className="fr">-e</td>
              </tr>
              <tr>
                <th scope="row">masculin pluriel</th>
                <td className="fr">Ils sont partis.</td>
                <td className="fr">-s</td>
              </tr>
              <tr>
                <th scope="row">féminin pluriel</th>
                <td className="fr">Elles sont parties.</td>
                <td className="fr">-es</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="attention">
          l’accord s’entend rarement. <span className="fr">parti</span> et{" "}
          <span className="fr">partie</span> se prononcent de la même façon :
          c’est une règle d’écriture, et elle se voit seulement sur la page.
        </div>

        <div className="astuce">
          <p className="astuce-hook">
            Le verbe change d’auxiliaire quand il change de sens
          </p>
          <p>
            Quelques verbes de la liste prennent{" "}
            <span className="fr">avoir</span> lorsqu’ils sont suivis d’un
            complément : <span className="fr">Je suis sorti</span> (je suis
            allé dehors) mais <span className="fr">J’ai sorti la poubelle</span>{" "}
            (j’ai sorti quelque chose). Même chose pour{" "}
            <span className="fr">monter</span>,{" "}
            <span className="fr">descendre</span> et{" "}
            <span className="fr">passer</span>.
          </p>
        </div>
      </section>

      <section>
        <h2>À la forme négative</h2>

        <div className="rule">
          <span className="fr">ne</span> et <span className="fr">pas</span>{" "}
          entourent <strong>l’auxiliaire</strong>, jamais le participe passé.
        </div>

        <div className="example">
          Je <strong>n’</strong>ai <strong>pas</strong> compris. · Elle{" "}
          <strong>n’</strong>est <strong>pas</strong> venue. · Nous{" "}
          <strong>n’</strong>avons <strong>jamais</strong> vu ce film.
        </div>

        <div className="attention">
          à l’oral, le <span className="fr">ne</span> disparaît souvent —{" "}
          <span className="fr">j’ai pas compris</span>. On l’entend peu, mais à
          l’écrit il est obligatoire.
        </div>
      </section>
    </article>
  );
}

// src/views/grammaire/le-passe-compose.vue
<!-- view-meta: created=2026-08-03; updated=2026-08-03 -->
<template>
  <AltLayout title="Le passé composé">
    <main class="lesson">

      <!-- ── Règle principale ───────────────────────── -->
      <article>
        <div class="rule">
          Le <strong class="hl-blue">passé composé</strong> s'utilise pour exprimer une action ponctuelle et terminée dans le passé.
          En espagnol, il correspond au <strong class="hl-blue">«&nbsp;pretérito perfecto compuesto&nbsp;»</strong> (<em>he hablado</em>) ou au <strong class="hl-blue">«&nbsp;pretérito indefinido&nbsp;»</strong> (<em>hablé</em>).
          <br><br>
          <strong class="hl-red">Attention !</strong> En espagnol, on utilise toujours l'auxiliaire <em>haber</em>. En français, on utilise l'auxiliaire <strong class="hl-blue">avoir</strong> ou <strong class="hl-blue">être</strong> selon le verbe.
        </div>
      </article>

      <!-- ── 1. Passé composé avec AVOIR ────────────── -->
      <article>
        <h2>1. Le passé composé avec <em>avoir</em> (la majorité des verbes)</h2>
        <p class="method">
          Il se forme avec l'auxiliaire <strong class="hl-blue">avoir</strong> au présent + le <strong class="hl-blue">participe passé</strong> du verbe principal.
        </p>

        <p class="method-example">
          <strong>avoir</strong> (présent)
          <span class="arrow-inline" aria-hidden="true">+</span>
          <strong>participe passé</strong>
        </p>

        <table>
          <caption class="sr-only">Conjugaison du passé composé avec l'auxiliaire avoir</caption>
          <thead>
            <tr>
              <th>Pronom</th>
              <th>Auxiliaire (avoir)</th>
              <th>Participe passé</th>
              <th>Traducción (ES)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="person">j'</td>
              <td class="aux">ai</td>
              <td><span class="inf">parlé</span></td>
              <td class="translation">he hablado / hablé</td>
            </tr>
            <tr>
              <td class="person">tu</td>
              <td class="aux">as</td>
              <td><span class="inf">fini</span></td>
              <td class="translation">has terminado / terminaste</td>
            </tr>
            <tr>
              <td class="person">il / elle / on</td>
              <td class="aux">a</td>
              <td><span class="inf">mangé</span></td>
              <td class="translation">ha comido / comió</td>
            </tr>
            <tr>
              <td class="person">nous</td>
              <td class="aux">avons</td>
              <td><span class="inf">vendu</span></td>
              <td class="translation">hemos vendido / vendimos</td>
            </tr>
            <tr>
              <td class="person">vous</td>
              <td class="aux">avez</td>
              <td><span class="inf">appris</span></td>
              <td class="translation">habéis aprendido / aprendieron</td>
            </tr>
            <tr>
              <td class="person">ils / elles</td>
              <td class="aux">ont</td>
              <td><span class="inf">fait</span></td>
              <td class="translation">han hecho / hicieron</td>
            </tr>
          </tbody>
        </table>

        <h3>Formation des participes passés (par terminaison)</h3>
        <div class="example">
          <strong>1<sup>er</sup> groupe (-er)</strong> → <strong>-é</strong> : parler → parlé, visiter → visité, manger → mangé.
        </div>
        <div class="example">
          <strong>2<sup>e</sup> groupe (-ir)</strong> → <strong>-i</strong> : finir → fini, choisir → choisi.
        </div>
        <div class="example">
          <strong>3<sup>e</sup> groupe (verbes en -dre)</strong> :
          <br>
          • Verbes en <em>-andre, -endre, -ondre, -erdre</em> → <strong>-u</strong> : vendre → <strong>vendu</strong>, attendre → <strong>attendu</strong>, répondre → <strong>répondu</strong>.
          <br>
          • Verbes de la famille de <em>prendre</em> (-prendre) → <strong>-pris</strong> : prendre → <strong>pris</strong>, apprendre → <strong>appris</strong>, comprendre → <strong>compris</strong>.
        </div>

        <h3>Autres participes passés fréquents (3<sup>e</sup> groupe)</h3>
        <div class="example">
          avoir → <strong>eu</strong> · être → <strong>été</strong> · faire → <strong>fait</strong> · voir → <strong>vu</strong> · pouvoir → <strong>pu</strong> · vouloir → <strong>voulu</strong> · écrire → <strong>écrit</strong> · mettre → <strong>mis</strong>.
        </div>
      </article>

      <!-- ── 2. Passé composé avec ÊTRE ─────────────── -->
      <article>
        <h2>2. Le passé composé avec <em>être</em> (verbes de déplacement et verbes pronominaux)</h2>
        <div class="attention">
          On utilise l'auxiliaire <strong class="hl-blue">être</strong> avec <strong>14 verbes de déplacement/changement d'état</strong> (<em>aller, venir, arriver, partir, entrer, sortir, monter, descendre, naître, mourir, rester, tomber, retourner, passer</em>) ainsi qu'avec <strong>tous les verbes pronominaux</strong> (<em>se lever, se coucher...</em>).
        </div>

        <table>
          <caption class="sr-only">Exemples de conjugaison du passé composé avec l'auxiliaire être</caption>
          <thead>
            <tr>
              <th>Sujet</th>
              <th>Auxiliaire (être)</th>
              <th>Participe passé</th>
              <th>Traducción (ES)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="person">il</td>
              <td class="aux">est</td>
              <td><span class="inf">allé</span></td>
              <td class="translation">él ha ido / fue</td>
            </tr>
            <tr>
              <td class="person">elle</td>
              <td class="aux">est</td>
              <td><span class="inf">allée</span> <span class="note">(+e)</span></td>
              <td class="translation">ella ha ido / fue</td>
            </tr>
            <tr>
              <td class="person">ils</td>
              <td class="aux">sont</td>
              <td><span class="inf">partis</span> <span class="note">(+s)</span></td>
              <td class="translation">ellos han salido / salieron</td>
            </tr>
            <tr>
              <td class="person">elles</td>
              <td class="aux">sont</td>
              <td><span class="inf">parties</span> <span class="note">(+es)</span></td>
              <td class="translation">ellas han salido / salieron</td>
            </tr>
          </tbody>
        </table>

        <div class="rule">
          <strong class="hl-red">Règle essentielle d'accord :</strong> Avec l'auxiliaire <em>être</em>, le participe passé <strong class="hl-blue">s'accorde toujours en genre et en nombre</strong> avec le sujet (masculin/féminin, singulier/pluriel).
        </div>
      </article>

      <!-- ── 3. La Négation ─────────────────────────── -->
      <article>
        <div class="exception">
          <strong>La négation</strong> : les mots <strong class="hl-red">ne... pas</strong> encadrent <strong>uniquement l'auxiliaire</strong> (avoir ou être). Le participe passé se place après le «&nbsp;pas&nbsp;».
        </div>
        <div class="example exception-ex">
          Je <strong class="hl-red">n'</strong>ai <strong class="hl-red">pas</strong> compris.
          <span class="sep">·</span>
          Elle <strong class="hl-red">n'</strong>est <strong class="hl-red">pas</strong> venue.
          <span class="sep">·</span>
          Nous <strong class="hl-red">ne</strong> sommes <strong class="hl-red">pas</strong> sortis.
        </div>
      </article>

      <button
        class="download-btn"
        @click="downloadPdf"
        aria-label="Télécharger cette leçon en PDF"
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M12 3v14m0 0-5-5m5 5 5-5"/>
          <path d="M3 20h18"/>
        </svg>
        <span>Télécharger</span>
      </button>

      <RelatedLinks />

    </main>
  </AltLayout>
</template>

<script setup>
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'

function downloadPdf() {
  window.print()
}
</script>

<style scoped>
.lesson {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.hl-blue { color: var(--clr-blue); font-weight: 700; }
.hl-red  { color: var(--clr-red);  font-weight: 700; }

.note {
  color: var(--clr-ink-soft);
  font-size: 0.82em;
  font-style: italic;
}

.method {
  line-height: 1.65;
  margin-bottom: 0.5rem;
}

.method-example {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.6rem 0.9rem;
  background: var(--clr-blue-light);
  border-radius: var(--radius);
  color: var(--clr-blue-dark);
  font-size: 0.92rem;
  margin-bottom: 0.75rem;
}

.arrow-inline {
  color: var(--clr-blue);
  font-weight: 700;
}

table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 0.75rem;
  font-size: 0.92rem;
}

th {
  background: var(--clr-blue);
  color: var(--text-on-accent);
  text-align: left;
  padding: 0.5rem 0.75rem;
  font-weight: 600;
}

td {
  padding: 0.5rem 0.75rem;
  border-bottom: 1px solid var(--clr-border-soft);
}

tbody tr:nth-child(even) {
  background: var(--clr-blue-light);
}

.person {
  font-weight: 600;
  color: var(--clr-ink);
}

.aux {
  color: var(--clr-blue);
  font-weight: 700;
}

.inf {
  font-weight: 700;
}

.translation {
  color: var(--clr-ink-mid);
  font-style: italic;
}

.sep {
  color: var(--clr-border);
  margin: 0 0.35rem;
}

h2 {
  font-family: var(--font-serif);
  font-size: 1.15rem;
  color: var(--clr-blue-dark);
  margin-top: 1rem;
  margin-bottom: 0.4rem;
}

h3 {
  font-family: var(--font-serif);
  font-size: 0.98rem;
  color: var(--clr-ink);
  margin-top: 0.75rem;
  margin-bottom: 0.35rem;
}

.download-btn {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.35rem;
  margin: 0.5rem auto 0;
  padding: 0.85rem 1.5rem;
  border: 1px solid var(--clr-border);
  border-radius: var(--radius);
  background: var(--clr-page);
  color: var(--clr-ink-soft);
  font-size: 0.72rem;
  letter-spacing: 0.1em;
  text-transform: uppercase;
  cursor: pointer;
  transition: border-color 0.15s, color 0.15s;
}

.download-btn:hover {
  border-color: var(--clr-blue);
  color: var(--clr-blue);
}

@media print {
  .download-btn {
    display: none !important;
  }
}
</style>
