// src/app/grammaire/les-pronoms-cod-coi/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/grammaire/les-pronoms-cod-coi";

export const metadata = lessonMetadata(PATH);

export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>Le COD : le verbe va droit au complément</h2>

        <div className="rule">
          Le complément d’objet <strong>direct</strong> suit le verbe sans
          préposition. Pour ne pas répéter le mot, on le remplace par{" "}
          <span className="fr">le</span>, <span className="fr">la</span>,{" "}
          <span className="fr">les</span> — et le pronom se place{" "}
          <strong>devant le verbe</strong>.
        </div>

        <div className="example">
          Je regarde <strong>la télévision</strong>. → Je{" "}
          <strong>la</strong> regarde.
          <br />
          Tu connais <strong>mes parents</strong> ? → Tu{" "}
          <strong>les</strong> connais ?
        </div>

        <div className="table-wrap">
          <table>
            <caption>Les pronoms compléments d’objet direct</caption>
            <thead>
              <tr>
                <th scope="col">Il remplace</th>
                <th scope="col">Pronom</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">moi</th>
                <td className="fr">me</td>
                <td className="fr">Il me voit.</td>
              </tr>
              <tr>
                <th scope="row">toi</th>
                <td className="fr">te</td>
                <td className="fr">Je te comprends.</td>
              </tr>
              <tr>
                <th scope="row">un nom masculin</th>
                <td className="fr">le</td>
                <td className="fr">Ce livre ? Je le lis.</td>
              </tr>
              <tr>
                <th scope="row">un nom féminin</th>
                <td className="fr">la</td>
                <td className="fr">Cette robe ? Je la prends.</td>
              </tr>
              <tr>
                <th scope="row">un pluriel</th>
                <td className="fr">les</td>
                <td className="fr">Les clés ? Je les cherche.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="attention">
          devant une voyelle, <span className="fr">me</span>,{" "}
          <span className="fr">te</span>, <span className="fr">le</span> et{" "}
          <span className="fr">la</span> perdent leur voyelle :{" "}
          <span className="fr">Je l’écoute</span>,{" "}
          <span className="fr">Il m’attend</span>.
        </div>
      </section>

      <section>
        <h2>Le COI : le verbe passe par « à »</h2>

        <div className="rule">
          Le complément d’objet <strong>indirect</strong> est relié au verbe par
          la préposition <span className="fr">à</span>. Quand il désigne une
          personne, on le remplace par <span className="fr">lui</span> au
          singulier et <span className="fr">leur</span> au pluriel — sans
          distinguer le masculin du féminin.
        </div>

        <div className="example">
          Je téléphone <strong>à ma sœur</strong>. → Je{" "}
          <strong>lui</strong> téléphone.
          <br />
          Il parle <strong>à ses collègues</strong>. → Il{" "}
          <strong>leur</strong> parle.
        </div>

        <div className="table-wrap">
          <table>
            <caption>COD et COI : les formes qui changent</caption>
            <thead>
              <tr>
                <th scope="col">Personne</th>
                <th scope="col">COD</th>
                <th scope="col">COI</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">3ᵉ personne du singulier</th>
                <td className="fr">le / la</td>
                <td className="fr">lui</td>
              </tr>
              <tr>
                <th scope="row">3ᵉ personne du pluriel</th>
                <td className="fr">les</td>
                <td className="fr">leur</td>
              </tr>
              <tr>
                <th scope="row">les autres</th>
                <td className="fr">me, te, nous, vous</td>
                <td className="fr">me, te, nous, vous</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="astuce">
          <p className="astuce-hook">Posez la question au verbe</p>
          <p>
            <strong>Qui ?</strong> ou <strong>quoi ?</strong> sans préposition →
            c’est un COD. <strong>À qui ?</strong> → c’est un COI. Le piège est
            que les deux langues ne construisent pas les mêmes verbes de la même
            façon : on dit <span className="fr">téléphoner à quelqu’un</span>{" "}
            mais <span className="fr">appeler quelqu’un</span>. Apprenez la
            préposition avec le verbe, comme une seule et même chose.
          </p>
        </div>
      </section>

      <section>
        <h2>Où placer le pronom</h2>

        <div className="rule">
          Le pronom se place <strong>devant le verbe conjugué</strong>. Au passé
          composé, il passe donc devant l’auxiliaire ; à la forme négative,{" "}
          <span className="fr">ne</span> se met avant lui.
        </div>

        <div className="table-wrap">
          <table>
            <caption>La place du pronom selon la forme de la phrase</caption>
            <thead>
              <tr>
                <th scope="col">Forme</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">présent</th>
                <td className="fr">Je les invite.</td>
              </tr>
              <tr>
                <th scope="row">passé composé</th>
                <td className="fr">Je les ai invités.</td>
              </tr>
              <tr>
                <th scope="row">négation</th>
                <td className="fr">Je ne les invite pas.</td>
              </tr>
              <tr>
                <th scope="row">deux verbes</th>
                <td className="fr">Je vais les inviter.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="attention">
          quand un COD est placé avant le verbe, le participe passé s’accorde
          avec lui : <span className="fr">Je les ai invit<strong>és</strong></span>{" "}
          · <span className="fr">Cette lettre, je l’ai écrit<strong>e</strong></span>.
          L’accord ne s’entend pas toujours, mais il s’écrit.
        </div>

        <div className="exception">
          l’impératif affirmatif. Là, le pronom passe{" "}
          <strong>après</strong> le verbe, avec un trait d’union, et{" "}
          <span className="fr">me</span> devient{" "}
          <span className="fr">moi</span> : <span className="fr">Regarde-la !</span>{" "}
          · <span className="fr">Téléphone-moi !</span> À la forme négative, il
          reprend sa place habituelle : <span className="fr">Ne la regarde pas.</span>
        </div>
      </section>

      <div className="resume">
        <ul>
          <li>
            Le COD suit le verbe sans préposition. Il se remplace par{" "}
            <span className="fr">le</span>, <span className="fr">la</span>,{" "}
            <span className="fr">les</span>.
          </li>
          <li>
            Le COI est relié au verbe par <span className="fr">à</span>. Pour
            une personne, il se remplace par <span className="fr">lui</span> au
            singulier et <span className="fr">leur</span> au pluriel.
          </li>
          <li>
            Le pronom se place devant le verbe conjugué, donc devant
            l’auxiliaire au passé composé. Sauf à l’impératif affirmatif, où il
            passe après : <span className="fr">Regarde-la !</span>
          </li>
          <li>
            Devant une voyelle, <span className="fr">me</span>,{" "}
            <span className="fr">te</span>, <span className="fr">le</span> et{" "}
            <span className="fr">la</span> perdent leur voyelle :{" "}
            <span className="fr">Je l’écoute</span>.
          </li>
          <li>
            Quand le COD est placé avant le verbe, le participe passé s’accorde
            avec lui : <span className="fr">Je les ai invités</span>.
          </li>
        </ul>
      </div>
    </article>
  );
}

// src/views/grammaire/les-pronoms-cod-coi.vue
<!-- view-meta: created=2026-08-10; updated=2026-08-10 -->
<template>
  <AltLayout title="Les pronoms COD et COI">
    <main class="lesson">

      <!-- ── Règle ─────────────────────────────────── -->
      <article>
        <div class="rule">
          Pour ne pas répéter un nom, on le remplace par un <strong class="hl-blue">pronom</strong>.
          En français, ce pronom se place <strong class="hl-red">devant le verbe</strong>.
        </div>
        <div class="attention">
          💡 <strong>Tip para hispanohablantes&nbsp;:</strong> es tu <em>lo / la / le</em>
          (<em>lo veo, le hablo</em>) y va delante del verbo, <strong>igual que en español</strong>.
          La gran diferencia&nbsp;: en francés <strong class="hl-red">nunca</strong> se pega al final
          del infinitivo. <em>Voy a verlo</em> → <em>Je vais <strong>le</strong> voir</em>, jamás «&nbsp;voir-le&nbsp;».
        </div>
      </article>

      <!-- ── COD ────────────────────────────────────── -->
      <article>
        <h2>1. Le COD — sans préposition</h2>
        <p class="method">
          Le complément d'objet <strong>direct</strong> répond à la question
          <strong>qui&nbsp;?</strong> ou <strong>quoi&nbsp;?</strong> après le verbe.
        </p>

        <table>
          <caption class="sr-only">Les pronoms compléments d'objet direct</caption>
          <thead>
            <tr>
              <th>Pronom</th>
              <th>Remplace</th>
              <th>Exemple</th>
              <th>Traducción (ES)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="aux">me / m'</td>
              <td class="person">moi</td>
              <td>Il <strong>me</strong> regarde.</td>
              <td class="translation">Me mira.</td>
            </tr>
            <tr>
              <td class="aux">te / t'</td>
              <td class="person">toi</td>
              <td>Je <strong>te</strong> vois.</td>
              <td class="translation">Te veo.</td>
            </tr>
            <tr>
              <td class="aux">le / l'</td>
              <td class="person">un nom masculin</td>
              <td>Je <strong>le</strong> mange.</td>
              <td class="translation">Lo como.</td>
            </tr>
            <tr>
              <td class="aux">la / l'</td>
              <td class="person">un nom féminin</td>
              <td>Je <strong>la</strong> connais.</td>
              <td class="translation">La conozco.</td>
            </tr>
            <tr>
              <td class="aux">nous</td>
              <td class="person">nous</td>
              <td>Elle <strong>nous</strong> invite.</td>
              <td class="translation">Nos invita.</td>
            </tr>
            <tr>
              <td class="aux">vous</td>
              <td class="person">vous</td>
              <td>Je <strong>vous</strong> écoute.</td>
              <td class="translation">Os escucho.</td>
            </tr>
            <tr>
              <td class="aux">les</td>
              <td class="person">un pluriel</td>
              <td>Je <strong>les</strong> achète.</td>
              <td class="translation">Los / las compro.</td>
            </tr>
          </tbody>
        </table>

        <div class="example">
          Tu regardes <strong>le film</strong>&nbsp;?
          <span class="arrow-inline" aria-hidden="true">→</span>
          Oui, je <strong class="hl-blue">le</strong> regarde.
        </div>
      </article>

      <!-- ── COI ────────────────────────────────────── -->
      <article>
        <h2>2. Le COI — avec la préposition «&nbsp;à&nbsp;»</h2>
        <p class="method">
          Le complément d'objet <strong>indirect</strong> répond à <strong>à qui&nbsp;?</strong>
          Seules les 3<sup>es</sup> personnes changent&nbsp;: <strong class="hl-blue">lui</strong> et
          <strong class="hl-blue">leur</strong>.
        </p>

        <table>
          <caption class="sr-only">Les pronoms compléments d'objet indirect</caption>
          <thead>
            <tr>
              <th>Pronom</th>
              <th>Exemple</th>
              <th>Traducción (ES)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="aux">me, te, nous, vous</td>
              <td>Il <strong>me</strong> parle.</td>
              <td class="translation">Me habla.</td>
            </tr>
            <tr>
              <td class="aux">lui</td>
              <td>Je <strong>lui</strong> téléphone.</td>
              <td class="translation">Le llamo (a él / a ella).</td>
            </tr>
            <tr>
              <td class="aux">leur</td>
              <td>Je <strong>leur</strong> écris.</td>
              <td class="translation">Les escribo.</td>
            </tr>
          </tbody>
        </table>

        <div class="attention">
          <strong>lui</strong> sert pour le masculin <em>et</em> le féminin. Et
          <strong class="hl-red">leur</strong> pronom ne prend <strong>jamais de -s</strong>&nbsp;:
          ne le confondez pas avec <em>leurs amis</em> (déterminant possessif).
        </div>
      </article>

      <!-- ── Exceptions ─────────────────────────────── -->
      <article>
        <div class="exception">
          <strong>La place du pronom.</strong> Toujours devant le verbe conjugué — sauf avec un
          infinitif, où il se place devant l'<strong>infinitif</strong>. Au passé composé, il passe
          devant l'auxiliaire.
        </div>
        <div class="example exception-ex">
          Je <strong class="hl-red">le</strong> vois.
          <span class="sep">·</span>
          Je vais <strong class="hl-red">le</strong> voir.
          <span class="sep">·</span>
          Je <strong class="hl-red">l'</strong>ai vu.
          <span class="sep">·</span>
          Je ne <strong class="hl-red">le</strong> vois pas.
        </div>
      </article>

      <button
        class="download-btn"
        @click="downloadPdf"
        aria-label="Télécharger cette leçon en PDF"
      >
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
          <path d="M12 3v14m0 0-5-5m5 5 5-5"/>
          <path d="M3 20h18"/>
        </svg>
        <span>Télécharger</span>
      </button>

      <RelatedLinks />

    </main>
  </AltLayout>
</template>

<script setup>
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'

function downloadPdf() {
  window.print()
}
</script>
