// src/views/musique/la-vie-en-rose.vue
<!-- view-meta: created=2026-08-26; updated=2026-08-26 -->
<template>
  <AltLayout title="La vie en rose">
    <main class="lesson">

      <p class="source-tag">
        Édith Piaf · paroles d'Édith Piaf, musique de Louiguy · 1945
      </p>

      <!-- ── 1. La chanson ──────────────────────────── -->
      <article>
        <h2>1. La chanson</h2>

        <p>
          Édith Piaf écrit <em>La vie en rose</em> en 1945, juste après la guerre. C'est
          aujourd'hui la chanson française la plus connue à l'étranger.
        </p>

        <div class="rule">
          Le titre vient d'une expression&nbsp;: <strong class="hl-blue">voir la vie en rose</strong>,
          c'est-à-dire voir la vie de façon heureuse, positive.
          <span class="translation">En español&nbsp;: <em>ver la vida de color de rosa</em> — la misma imagen.</span>
        </div>

        <div class="attention">
          <strong>Attention&nbsp;:</strong> en français la couleur du bonheur est le
          <strong>rose</strong>, jamais le rouge. <em>Voir la vie en rouge</em> ne veut rien dire.
        </div>

        <h3>Le refrain, vers par vers</h3>

        <p class="parole">
          «&nbsp;Quand il me <span class="hl-word" title="tomar / coger">prend</span> dans ses
          <span class="hl-word" title="brazos">bras</span>,<br>
          Il me parle <span class="hl-word" title="en voz baja">tout bas</span>,<br>
          Je vois la vie en rose.&nbsp;»
        </p>
        <p class="parole-es">
          Cuando me toma en sus brazos, me habla en voz baja, veo la vida de color de rosa.
        </p>

        <p class="parole">
          «&nbsp;Il me dit des mots d'amour,<br>
          Des mots de tous les jours,<br>
          Et ça me fait quelque chose.&nbsp;»
        </p>
        <p class="parole-es">
          Me dice palabras de amor, palabras de todos los días, y eso me hace algo (me emociona).
        </p>

        <p class="note">
          Tout l'art de Piaf est là&nbsp;: « des mots de tous les jours ». Le refrain est
          du français de niveau A2 — vous connaissez déjà presque tous ces mots.
        </p>
      </article>

      <!-- ── 2. Grammaire ───────────────────────────── -->
      <article>
        <h2>2. Deux points de grammaire</h2>

        <h3>Le pronom devant le verbe</h3>

        <p>
          <em>Il <strong class="hl-blue">me</strong> prend</em>, <em>il <strong class="hl-blue">me</strong> parle</em>,
          <em>il <strong class="hl-blue">me</strong> dit</em>&nbsp;: en français le pronom se place
          <strong>avant</strong> le verbe — exactement comme en espagnol.
        </p>

        <div class="example">
          Il <strong>me</strong> prend dans ses bras. <span class="sep">·</span> <em>Me toma en sus brazos.</em><br>
          Il <strong>me</strong> parle tout bas. <span class="sep">·</span> <em>Me habla en voz baja.</em>
        </div>

        <p class="sep">
          <RouterLink class="lesson-link" to="/grammaire/les-pronoms-cod-coi">
            Voir la leçon complète&nbsp;: Les pronoms COD et COI
          </RouterLink><br>
          <RouterLink class="lesson-link" to="/exercices/le-bon-pronom">
            S'entraîner&nbsp;: la manche chronométrée « Le bon pronom »
          </RouterLink>
        </p>

        <h3>Les pronoms toniques</h3>

        <p>
          Le dernier couplet dit&nbsp;: «&nbsp;C'est <strong class="hl-blue">lui</strong> pour
          <strong class="hl-blue">moi</strong>, <strong class="hl-blue">moi</strong> pour
          <strong class="hl-blue">lui</strong>&nbsp;». Après une préposition
          (<em>pour</em>, <em>avec</em>, <em>chez</em>…), le français n'utilise jamais
          <em>je</em> ou <em>il</em>, mais <strong>moi</strong>, <strong>toi</strong>,
          <strong>lui</strong>, <strong>elle</strong>.
        </p>

        <div class="exception">
          On dit <em>pour <strong>moi</strong></em>, jamais <em class="hl-red">pour je</em>.
          <div class="exception-ex">c'est lui pour moi <span class="sep">·</span> <em>es él para mí</em></div>
        </div>
      </article>

      <!-- ── 3. Vocabulaire ─────────────────────────── -->
      <article>
        <h2>3. Vocabulaire de la chanson</h2>

        <table class="dense">
          <caption class="sr-only">Vocabulaire de la chanson La vie en rose, avec définition et traduction en espagnol</caption>
          <thead>
            <tr>
              <th>Mot</th>
              <th>Définition en français</th>
              <th>En español</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="inf">prendre dans ses bras</td>
              <td>serrer quelqu'un contre soi</td>
              <td class="translation">tomar en sus brazos, abrazar</td>
            </tr>
            <tr>
              <td class="inf">tout bas</td>
              <td>très doucement, presque sans voix</td>
              <td class="translation">en voz baja</td>
            </tr>
            <tr>
              <td class="inf">un mot d'amour</td>
              <td>une parole tendre</td>
              <td class="translation">una palabra de amor</td>
            </tr>
            <tr>
              <td class="inf">le bonheur</td>
              <td>le sentiment d'être heureux</td>
              <td class="translation">la felicidad</td>
            </tr>
            <tr>
              <td class="inf">la peine</td>
              <td>la tristesse, la douleur</td>
              <td class="translation">la pena</td>
            </tr>
            <tr>
              <td class="inf">un serment</td>
              <td>une promesse solennelle</td>
              <td class="translation">un juramento</td>
            </tr>
            <tr>
              <td class="inf">un frisson</td>
              <td>un petit tremblement d'émotion</td>
              <td class="translation">un escalofrío</td>
            </tr>
            <tr>
              <td class="inf">le cœur</td>
              <td>l'organe, et le siège des sentiments</td>
              <td class="translation">el corazón</td>
            </tr>
          </tbody>
        </table>

      </article>

      <RelatedLinks />
    </main>
  </AltLayout>
</template>

<script setup>
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'
</script>

<style scoped>
/* Song-page chrome: a quoted verse and its Spanish gloss. Nothing else here —
   the rest of the page uses the global `.lesson` classes. */
.source-tag {
  font-family: var(--font-mono);
  font-size: 0.78rem;
  color: var(--text-3);
  text-align: center;
  border-bottom: 1px dashed var(--border);
  padding-bottom: 0.6rem;
  margin: 0;
}

/* h3 has no global top margin; after a callout card it reads as cramped. */
h3 { margin-top: 0.7rem; }

.parole {
  font-family: var(--font-serif);
  font-size: 1.05rem;
  line-height: 1.75;
  color: var(--text-heading);
  background: var(--accent-soft);
  border-left: 4px solid var(--accent);
  border-radius: var(--radius-sm);
  padding: 0.75rem 1rem;
  margin: 0 0 0.4rem;
}

.parole-es {
  font-size: 0.85rem;
  font-style: italic;
  color: var(--text-3);
  margin: 0 0 1rem;
}

.hl-word {
  border-bottom: 1px dashed var(--accent);
  color: var(--accent-text);
  font-weight: 600;
  cursor: help;
}
</style>

// src/app/musique/la-vie-en-rose/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/musique/la-vie-en-rose";

export const metadata = lessonMetadata(PATH);

export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>Une expression, puis une chanson</h2>

        <p>
          Paroles d’Édith Piaf, musique de Louiguy, 1945. Piaf l’enregistre
          l’année suivante, et c’est devenu la chanson française la plus connue
          hors de France.
        </p>

        <div className="rule">
          Le titre vient d’une expression qui existait avant la chanson :{" "}
          <span className="fr">voir la vie en rose</span>, c’est voir la vie du
          bon côté, être heureux au point que tout paraît beau.
        </div>

        <div className="attention">
          en français, la couleur du bonheur est le{" "}
          <span className="fr">rose</span>, jamais le rouge.{" "}
          <span className="fr">voir la vie en rouge</span> ne veut rien dire. La
          couleur des idées noires, elle, est bien le noir :{" "}
          <span className="fr">broyer du noir</span>, c’est être triste.
        </div>

        <p>
          L’expression s’emploie encore aujourd’hui, souvent au négatif pour
          dire qu’on est lucide : <span className="fr">je ne vois pas la vie en
          rose</span>, ou <span className="fr">il voit tout en rose</span> pour
          dire de quelqu’un qu’il est un peu naïf.
        </p>
      </section>

      <section>
        <h2>Le refrain, mot à mot</h2>

        <p>
          Trois vers suffisent à montrer pourquoi cette chanson se retient : il
          n’y a pas un mot rare dedans.
        </p>

        <div className="example">
          <p>
            Quand il me prend dans ses bras,
            <br />
            Il me parle tout bas,
            <br />
            Je vois la vie en rose.
          </p>
        </div>

        <div className="table-wrap">
          <table>
            <caption>Les trois expressions du refrain, définies</caption>
            <thead>
              <tr>
                <th scope="col">Expression</th>
                <th scope="col">Définition</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  prendre dans ses bras
                </th>
                <td>serrer quelqu’un contre soi</td>
                <td className="fr">
                  Elle a pris son fils dans ses bras avant de partir.
                </td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  tout bas
                </th>
                <td>très doucement, presque sans voix</td>
                <td className="fr">Il a répondu tout bas, pour ne pas réveiller le bébé.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  voir la vie en rose
                </th>
                <td>trouver que tout est beau, être heureux</td>
                <td className="fr">Depuis qu’elle a ce travail, elle voit la vie en rose.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="rule">
          <span className="fr">il me prend</span>,{" "}
          <span className="fr">il me parle</span> : le pronom se place{" "}
          <strong>avant</strong> le verbe, et jamais après. C’est la règle
          générale en français, et le refrain la donne deux fois de suite.
        </div>
      </section>

      <section>
        <h2>« C’est lui pour moi » : les pronoms toniques</h2>

        <p>
          Plus loin, la chanson dit{" "}
          <span className="fr">c’est lui pour moi, moi pour lui</span>. Ce{" "}
          <span className="fr">moi</span> n’est pas le même mot que le{" "}
          <span className="fr">me</span> du refrain : après une préposition, le
          français emploie une autre série de pronoms.
        </p>

        <div className="table-wrap">
          <table>
            <caption>
              La forme qu’un pronom prend après pour, avec, chez, sans
            </caption>
            <thead>
              <tr>
                <th scope="col">Sujet</th>
                <th scope="col">Après une préposition</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  je
                </th>
                <td className="fr">moi</td>
                <td className="fr">C’est pour moi.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  tu
                </th>
                <td className="fr">toi</td>
                <td className="fr">Je viens avec toi.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  il / elle
                </th>
                <td className="fr">lui / elle</td>
                <td className="fr">Nous dînons chez lui.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  nous / vous
                </th>
                <td className="fr">nous / vous</td>
                <td className="fr">Il est parti sans nous.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ils / elles
                </th>
                <td className="fr">eux / elles</td>
                <td className="fr">Elle travaille pour eux.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="exception">
          on dit <span className="fr">pour moi</span>, jamais{" "}
          <span className="fr">pour je</span>. Deux formes seulement se
          ressemblent d’une colonne à l’autre,{" "}
          <span className="fr">nous</span> et <span className="fr">vous</span> ;
          toutes les autres changent, et{" "}
          <span className="fr">eux</span> n’existe que dans cette colonne.
        </div>
      </section>

      <div className="resume">
        <h2>En résumé</h2>
        <ul>
          <li>
            <span className="fr">voir la vie en rose</span> veut dire trouver
            que tout est beau ; la chanson est née de l’expression, pas
            l’inverse.
          </li>
          <li>
            La couleur du bonheur est le rose, celle de la tristesse le noir.
          </li>
          <li>
            Le refrain ne contient aucun mot rare : c’est ce qui le rend
            chantable au bout de trois écoutes.
          </li>
          <li>
            <span className="fr">me</span>, <span className="fr">te</span>,{" "}
            <span className="fr">le</span> se placent avant le verbe.
          </li>
          <li>
            Après <span className="fr">pour</span>,{" "}
            <span className="fr">avec</span>, <span className="fr">chez</span>,{" "}
            <span className="fr">sans</span>, on emploie{" "}
            <span className="fr">moi</span>, <span className="fr">toi</span>,{" "}
            <span className="fr">lui</span>, <span className="fr">eux</span>.
          </li>
        </ul>
      </div>
    </article>
  );
}
