// src/views/grammaire/la-negation.vue
<!-- view-meta: created=2026-08-02; updated=2026-08-26 -->
<template>
  <AltLayout title="La négation">
    <main class="lesson">

      <!-- ── Règle ─────────────────────────────────── -->
      <article>
        <div class="rule">
          Pour rendre une phrase négative, on encadre le
          <strong class="hl-blue">verbe conjugué</strong> avec deux mots :
          <strong class="hl-red">ne</strong> ... <strong class="hl-red">pas</strong>.
        </div>

        <div class="method-example">
          <strong>Je parle.</strong>
          <span class="arrow-inline" aria-hidden="true">→</span>
          Je <strong class="hl-red">ne</strong> parle <strong class="hl-red">pas</strong>.
        </div>
      </article>

      <!-- ── Construction ──────────────────────────── -->
      <article>
        <h2>La construction</h2>
        <p class="method">
          <strong class="hl-red">ne</strong> se place
          <strong class="hl-blue">avant</strong> le verbe,
          <strong class="hl-red">pas</strong> se place
          <strong class="hl-blue">après</strong>.
        </p>

        <table>
          <caption class="sr-only">Construction de la négation avec ne...pas</caption>
          <thead>
            <tr>
              <th>Sujet</th>
              <th class="col-neg">ne</th>
              <th>Verbe</th>
              <th class="col-neg">pas</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="person">je</td>
              <td class="neg">ne</td>
              <td><span class="stem">parl</span><span class="end">e</span></td>
              <td class="neg">pas</td>
            </tr>
            <tr>
              <td class="person">tu</td>
              <td class="neg">ne</td>
              <td><span class="stem">mang</span><span class="end">es</span></td>
              <td class="neg">pas</td>
            </tr>
            <tr>
              <td class="person">il / elle</td>
              <td class="neg">ne</td>
              <td><span class="stem">fin</span><span class="end">it</span></td>
              <td class="neg">pas</td>
            </tr>
            <tr>
              <td class="person">nous</td>
              <td class="neg">ne</td>
              <td><span class="stem">ven</span><span class="end">ons</span></td>
              <td class="neg">pas</td>
            </tr>
          </tbody>
        </table>

        <div class="example">
          Elle <strong class="hl-red">ne</strong> travaille <strong class="hl-red">pas</strong> le dimanche.
        </div>
        <div class="example">
          Nous <strong class="hl-red">ne</strong> comprenons <strong class="hl-red">pas</strong> la question.
        </div>
        <div class="example">
          Ils <strong class="hl-red">ne</strong> sont <strong class="hl-red">pas</strong> français.
        </div>
      </article>

      <!-- ── À retenir : élision ────────────────────── -->
      <article>
        <div class="attention">
          Devant une <mark>voyelle</mark> ou un <mark>h muet</mark>,
          <strong class="hl-red">ne</strong> devient
          <strong class="hl-red">n'</strong>.
        </div>
        <div class="example exception-ex">
          Je <strong class="hl-red">n'</strong>aime pas le café.
          <span class="sep">·</span>
          Il <strong class="hl-red">n'</strong>habite pas ici.
        </div>
      </article>

      <!-- ── Exception : articles après la négation ── -->
      <article>
        <div class="exception">
          <strong>Les articles indéfinis et partitifs</strong>
          (un, une, des, du, de la, de l') deviennent
          <strong class="hl-red">de</strong> (ou
          <strong class="hl-red">d'</strong> devant une voyelle) après une
          négation.
        </div>
        <div class="example exception-ex">
          J'ai <strong class="hl-blue">un</strong> vélo
          <span class="arrow-inline" aria-hidden="true">→</span>
          Je n'ai pas <strong class="hl-red">de</strong> vélo
        </div>
        <div class="example exception-ex">
          Elle boit <strong class="hl-blue">du</strong> thé
          <span class="arrow-inline" aria-hidden="true">→</span>
          Elle ne boit pas <strong class="hl-red">de</strong> thé
        </div>
        <div class="example" style="margin-top: 0.5rem;">
          Il n'y a pas <strong class="hl-red">d'</strong>eau dans le verre.
          <span class="note">(de + voyelle → d')</span>
        </div>
      </article>

      <!-- ── Autres négations ──────────────────────── -->
      <article>
        <h2>D'autres mots de négation</h2>
        <p class="method">
          <strong class="hl-red">pas</strong> peut être remplacé par d'autres
          mots pour préciser le sens de la négation.
        </p>

        <table>
          <caption class="sr-only">Autres formes de négation</caption>
          <thead>
            <tr>
              <th>Négation</th>
              <th>Sens</th>
              <th>Exemple</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="neg-form">ne ... plus</td>
              <td class="sense">fin d'une action</td>
              <td>Je <strong class="hl-red">ne</strong> fume <strong class="hl-red">plus</strong>.</td>
            </tr>
            <tr>
              <td class="neg-form">ne ... jamais</td>
              <td class="sense">zéro fois</td>
              <td>Il <strong class="hl-red">ne</strong> ment <strong class="hl-red">jamais</strong>.</td>
            </tr>
            <tr>
              <td class="neg-form">ne ... rien</td>
              <td class="sense">aucune chose</td>
              <td>Elle <strong class="hl-red">ne</strong> voit <strong class="hl-red">rien</strong>.</td>
            </tr>
            <tr>
              <td class="neg-form">ne ... personne</td>
              <td class="sense">aucune personne</td>
              <td>Nous <strong class="hl-red">ne</strong> connaissons <strong class="hl-red">personne</strong>.</td>
            </tr>
          </tbody>
        </table>
      </article>

      <RelatedLinks />
    </main>
  </AltLayout>
</template>

<script setup>
import AltLayout from '@/layouts/AltLayout.vue'
import RelatedLinks from '@/components/RelatedLinks.vue'
</script>

<style scoped>
.lesson {
  gap: 1rem;
}

/* ── Inline typography helpers ─────────────────── */
.hl-blue { color: var(--clr-blue); font-weight: 700; }
.hl-red  { color: var(--clr-red);  font-weight: 700; }

.end     { color: var(--clr-red); }
.stem    { color: var(--clr-blue); font-weight: 600; }

mark {
  background: var(--clr-amber-light);
  color: var(--clr-amber);
  padding: 0.05em 0.25em;
  border-radius: 2px;
  font-style: normal;
  font-weight: 600;
}

.note {
  color: var(--clr-ink-soft);
  font-size: 0.82em;
  font-style: italic;
}

.sep {
  color: var(--clr-border);
  margin: 0 0.25rem;
}

.arrow-inline {
  color: var(--clr-blue-mid);
}

/* ── Method line ───────────────────────────────── */
.method {
  color: var(--clr-ink-mid);
  font-size: 0.9rem;
  margin-bottom: 0.35rem;
}

.method-example {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.5rem;
  font-size: 0.97rem;
  margin-top: 1rem;
}

/* ── Table ─────────────────────────────────────── */
table {
  width: 100%;
  border-collapse: collapse;
  margin-bottom: 1rem;
  font-size: 0.92rem;
}

caption.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip: rect(0 0 0 0);
}

th {
  background: var(--clr-blue);
  color: var(--text-on-accent);
  padding: 0.5rem 0.75rem;
  text-align: left;
  font-family: var(--font-sans);
  font-weight: 700;
  font-size: 0.72rem;
  letter-spacing: 0.05em;
  text-transform: uppercase;
}

th.col-neg {
  background: var(--clr-red);
}

td {
  padding: 0.45rem 0.75rem;
  border-bottom: 1px solid var(--clr-border-soft);
  color: var(--clr-ink);
}

td.person {
  color: var(--clr-ink-mid);
  font-size: 0.85rem;
  font-style: italic;
  white-space: nowrap;
}

td.neg {
  font-family: var(--font-mono);
  font-weight: 700;
  color: var(--clr-red);
}

td.neg-form {
  font-family: var(--font-mono);
  font-weight: 700;
  color: var(--clr-red);
  white-space: nowrap;
}

td.sense {
  color: var(--clr-ink-mid);
  font-size: 0.85rem;
  font-style: italic;
}

tr:last-child td {
  border-bottom: none;
}

tr:nth-child(even) td {
  background: var(--clr-blue-light);
}

/* ── Examples ──────────────────────────────────── */
.example + .example {
  margin-top: 0.5rem;
}

.exception-ex {
  margin-top: 0.6rem;
  font-family: var(--font-mono);
  font-size: 0.9rem;
}

/* ── Download button ───────────────────────────── */
</style>

// src/app/grammaire/la-negation/page.tsx
import { lessonMetadata } from "@/components/lesson/metadata";
import { PageHeader } from "@/components/lesson/PageHeader";

const PATH = "/grammaire/la-negation";

export const metadata = lessonMetadata(PATH);

export default function Page() {
  return (
    <article className="prose">
      <PageHeader path={PATH} />

      <section>
        <h2>Deux mots autour du verbe</h2>

        <div className="rule">
          La négation française s’écrit en <strong>deux morceaux</strong>.{" "}
          <span className="fr">ne</span> se met avant le verbe conjugué,{" "}
          <span className="fr">pas</span> se met après. Le verbe est pris entre
          les deux.
        </div>

        <div className="example">
          Je parle. → Je <strong>ne</strong> parle <strong>pas</strong>.
          <br />
          Elle travaille le dimanche. → Elle <strong>ne</strong> travaille{" "}
          <strong>pas</strong> le dimanche.
          <br />
          Ils sont français. → Ils <strong>ne</strong> sont{" "}
          <strong>pas</strong> français.
        </div>

        <p>
          Devant une voyelle ou un <span className="fr">h</span> muet,{" "}
          <span className="fr">ne</span> devient{" "}
          <span className="fr">n’</span>.
        </p>

        <div className="example">
          Je <strong>n’</strong>aime pas le café. · Il <strong>n’</strong>habite
          pas ici. · On <strong>n’</strong>a pas le temps.
        </div>

        <div className="attention">
          au passé composé, les deux morceaux encadrent{" "}
          <strong>l’auxiliaire</strong>, pas le participe :{" "}
          <span className="fr">je n’ai pas mangé</span>,{" "}
          <span className="fr">elle n’est pas venue</span>. Le participe reste
          en dehors, après <span className="fr">pas</span>.
        </div>

        <div className="astuce">
          <p className="astuce-hook">
            À l’oral, le <span className="fr">ne</span> disparaît. À l’écrit,
            jamais.
          </p>
          <p>
            On entend tous les jours{" "}
            <span className="fr">je sais pas</span>,{" "}
            <span className="fr">c’est pas grave</span>. C’est du français
            courant et vous pouvez le dire. Mais une phrase écrite sans{" "}
            <span className="fr">ne</span> est une phrase fausse : dans une
            lettre, un message professionnel ou un examen, les deux morceaux
            sont obligatoires.
          </p>
        </div>
      </section>

      <section>
        <h2>Après la négation, l’article change</h2>

        <div className="rule">
          <span className="fr">un</span>, <span className="fr">une</span>,{" "}
          <span className="fr">des</span>, <span className="fr">du</span>,{" "}
          <span className="fr">de la</span> deviennent{" "}
          <strong>
            <span className="fr">de</span>
          </strong>{" "}
          après une négation, quel que soit le genre et le nombre du nom.
        </div>

        <div className="table-wrap">
          <table>
            <caption>
              Ce que l’article devient quand la phrase passe au négatif
            </caption>
            <thead>
              <tr>
                <th scope="col">Phrase affirmative</th>
                <th scope="col">Phrase négative</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  J’ai un vélo.
                </th>
                <td className="fr">Je n’ai pas de vélo.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  Elle a une voiture.
                </th>
                <td className="fr">Elle n’a pas de voiture.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  Nous avons des enfants.
                </th>
                <td className="fr">Nous n’avons pas d’enfants.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  Il boit du thé.
                </th>
                <td className="fr">Il ne boit pas de thé.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p>
          Devant une voyelle, <span className="fr">de</span> s’élide à son tour
          et donne <span className="fr">d’</span> :{" "}
          <span className="fr">il n’y a pas d’eau dans le verre</span>.
        </p>

        <div className="exception">
          l’article défini ne bouge pas.{" "}
          <span className="fr">le</span>, <span className="fr">la</span>,{" "}
          <span className="fr">les</span> restent tels quels :{" "}
          <span className="fr">je n’aime pas le café</span>, jamais{" "}
          <span className="fr">je n’aime pas de café</span>. Et après le verbe{" "}
          <span className="fr">être</span>, rien ne change non plus :{" "}
          <span className="fr">ce n’est pas un problème</span>.
        </div>
      </section>

      <section>
        <h2>Quand « pas » cède sa place</h2>

        <p>
          <span className="fr">ne</span> reste toujours devant le verbe, mais le
          deuxième morceau peut changer pour préciser le sens de la négation.
        </p>

        <div className="table-wrap">
          <table>
            <caption>
              Les quatre négations qui remplacent « pas », et ce qu’elles disent
              de plus
            </caption>
            <thead>
              <tr>
                <th scope="col">Négation</th>
                <th scope="col">Sens</th>
                <th scope="col">Exemple</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row" className="fr">
                  ne … plus
                </th>
                <td>c’était vrai avant, c’est fini</td>
                <td className="fr">Je ne fume plus.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ne … jamais
                </th>
                <td>zéro fois, aucune fois</td>
                <td className="fr">Il ne ment jamais.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ne … rien
                </th>
                <td>aucune chose</td>
                <td className="fr">Elle ne voit rien.</td>
              </tr>
              <tr>
                <th scope="row" className="fr">
                  ne … personne
                </th>
                <td>aucune personne</td>
                <td className="fr">Nous ne connaissons personne.</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="attention">
          ces mots remplacent <span className="fr">pas</span>, ils ne
          s’ajoutent pas à lui. On dit{" "}
          <span className="fr">je ne fume plus</span>, jamais{" "}
          <span className="fr">je ne fume pas plus</span>.
        </div>

        <div className="exception">
          au passé composé, <span className="fr">personne</span> se place après
          le participe, alors que les trois autres restent devant :{" "}
          <span className="fr">je n’ai rien vu</span> mais{" "}
          <span className="fr">je n’ai vu personne</span>.
        </div>
      </section>

      <div className="resume">
        <h2>En résumé</h2>
        <ul>
          <li>
            <span className="fr">ne</span> avant le verbe conjugué,{" "}
            <span className="fr">pas</span> après : le verbe est entre les deux.
          </li>
          <li>
            Devant une voyelle, <span className="fr">ne</span> devient{" "}
            <span className="fr">n’</span>.
          </li>
          <li>
            Au passé composé, les deux morceaux encadrent l’auxiliaire ; le
            participe reste après.
          </li>
          <li>
            <span className="fr">un</span>, <span className="fr">une</span>,{" "}
            <span className="fr">des</span>, <span className="fr">du</span>,{" "}
            <span className="fr">de la</span> deviennent{" "}
            <span className="fr">de</span>. L’article défini, lui, ne change
            pas.
          </li>
          <li>
            <span className="fr">plus</span>,{" "}
            <span className="fr">jamais</span>, <span className="fr">rien</span>
            , <span className="fr">personne</span> prennent la place de{" "}
            <span className="fr">pas</span> et ne s’ajoutent jamais à lui.
          </li>
        </ul>
      </div>
    </article>
  );
}
